on:
  release:
    types: [ created ]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTFLAGS: "-C target-feature=-crt-static" # openssl
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          EXTRA_FILES: "README.md LICENSE"
          TOOLCHAIN_VERSION: stable
